/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedDealsIndexRouteImport } from './routes/_authenticated/deals.index'
import { Route as AuthenticatedDealsIdRouteImport } from './routes/_authenticated/deals_.$id'
import { Route as AuthenticatedDealsCalendarRouteImport } from './routes/_authenticated/deals.calendar'
import { Route as AuthenticatedCatalogSpacesRouteImport } from './routes/_authenticated/catalog.spaces'
import { Route as AuthenticatedCatalogRulesRouteImport } from './routes/_authenticated/catalog.rules'
import { Route as AuthenticatedCatalogFoodRouteImport } from './routes/_authenticated/catalog.food'
import { Route as AuthenticatedCatalogExtrasRouteImport } from './routes/_authenticated/catalog.extras'
import { Route as AuthenticatedCatalogBeveragesRouteImport } from './routes/_authenticated/catalog.beverages'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDealsIndexRoute = AuthenticatedDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDealsRoute,
} as any)
const AuthenticatedDealsIdRoute = AuthenticatedDealsIdRouteImport.update({
  id: '/deals_/$id',
  path: '/deals/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsCalendarRoute =
  AuthenticatedDealsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedDealsRoute,
  } as any)
const AuthenticatedCatalogSpacesRoute =
  AuthenticatedCatalogSpacesRouteImport.update({
    id: '/spaces',
    path: '/spaces',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogRulesRoute =
  AuthenticatedCatalogRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogFoodRoute =
  AuthenticatedCatalogFoodRouteImport.update({
    id: '/food',
    path: '/food',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogExtrasRoute =
  AuthenticatedCatalogExtrasRouteImport.update({
    id: '/extras',
    path: '/extras',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogBeveragesRoute =
  AuthenticatedCatalogBeveragesRouteImport.update({
    id: '/beverages',
    path: '/beverages',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/deals': typeof AuthenticatedDealsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/c/$token': typeof CTokenRoute
  '/d/$token': typeof DTokenRoute
  '/f/$slug': typeof FSlugRoute
  '/p/$token': typeof PTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/catalog/beverages': typeof AuthenticatedCatalogBeveragesRoute
  '/catalog/extras': typeof AuthenticatedCatalogExtrasRoute
  '/catalog/food': typeof AuthenticatedCatalogFoodRoute
  '/catalog/rules': typeof AuthenticatedCatalogRulesRoute
  '/catalog/spaces': typeof AuthenticatedCatalogSpacesRoute
  '/deals/calendar': typeof AuthenticatedDealsCalendarRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/deals/': typeof AuthenticatedDealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/c/$token': typeof CTokenRoute
  '/d/$token': typeof DTokenRoute
  '/f/$slug': typeof FSlugRoute
  '/p/$token': typeof PTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/catalog/beverages': typeof AuthenticatedCatalogBeveragesRoute
  '/catalog/extras': typeof AuthenticatedCatalogExtrasRoute
  '/catalog/food': typeof AuthenticatedCatalogFoodRoute
  '/catalog/rules': typeof AuthenticatedCatalogRulesRoute
  '/catalog/spaces': typeof AuthenticatedCatalogSpacesRoute
  '/deals/calendar': typeof AuthenticatedDealsCalendarRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/deals': typeof AuthenticatedDealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/_authenticated/deals': typeof AuthenticatedDealsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/c/$token': typeof CTokenRoute
  '/d/$token': typeof DTokenRoute
  '/f/$slug': typeof FSlugRoute
  '/p/$token': typeof PTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/catalog/beverages': typeof AuthenticatedCatalogBeveragesRoute
  '/_authenticated/catalog/extras': typeof AuthenticatedCatalogExtrasRoute
  '/_authenticated/catalog/food': typeof AuthenticatedCatalogFoodRoute
  '/_authenticated/catalog/rules': typeof AuthenticatedCatalogRulesRoute
  '/_authenticated/catalog/spaces': typeof AuthenticatedCatalogSpacesRoute
  '/_authenticated/deals/calendar': typeof AuthenticatedDealsCalendarRoute
  '/_authenticated/deals_/$id': typeof AuthenticatedDealsIdRoute
  '/_authenticated/deals/': typeof AuthenticatedDealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/catalog'
    | '/deals'
    | '/settings'
    | '/c/$token'
    | '/d/$token'
    | '/f/$slug'
    | '/p/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/catalog/beverages'
    | '/catalog/extras'
    | '/catalog/food'
    | '/catalog/rules'
    | '/catalog/spaces'
    | '/deals/calendar'
    | '/deals/$id'
    | '/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/catalog'
    | '/settings'
    | '/c/$token'
    | '/d/$token'
    | '/f/$slug'
    | '/p/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/catalog/beverages'
    | '/catalog/extras'
    | '/catalog/food'
    | '/catalog/rules'
    | '/catalog/spaces'
    | '/deals/calendar'
    | '/deals/$id'
    | '/deals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/catalog'
    | '/_authenticated/deals'
    | '/_authenticated/settings'
    | '/c/$token'
    | '/d/$token'
    | '/f/$slug'
    | '/p/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/catalog/beverages'
    | '/_authenticated/catalog/extras'
    | '/_authenticated/catalog/food'
    | '/_authenticated/catalog/rules'
    | '/_authenticated/catalog/spaces'
    | '/_authenticated/deals/calendar'
    | '/_authenticated/deals_/$id'
    | '/_authenticated/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CTokenRoute: typeof CTokenRoute
  DTokenRoute: typeof DTokenRoute
  FSlugRoute: typeof FSlugRoute
  PTokenRoute: typeof PTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/deals/': {
      id: '/_authenticated/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof AuthenticatedDealsIndexRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/_authenticated/deals_/$id': {
      id: '/_authenticated/deals_/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AuthenticatedDealsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals/calendar': {
      id: '/_authenticated/deals/calendar'
      path: '/calendar'
      fullPath: '/deals/calendar'
      preLoaderRoute: typeof AuthenticatedDealsCalendarRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/_authenticated/catalog/spaces': {
      id: '/_authenticated/catalog/spaces'
      path: '/spaces'
      fullPath: '/catalog/spaces'
      preLoaderRoute: typeof AuthenticatedCatalogSpacesRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/rules': {
      id: '/_authenticated/catalog/rules'
      path: '/rules'
      fullPath: '/catalog/rules'
      preLoaderRoute: typeof AuthenticatedCatalogRulesRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/food': {
      id: '/_authenticated/catalog/food'
      path: '/food'
      fullPath: '/catalog/food'
      preLoaderRoute: typeof AuthenticatedCatalogFoodRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/extras': {
      id: '/_authenticated/catalog/extras'
      path: '/extras'
      fullPath: '/catalog/extras'
      preLoaderRoute: typeof AuthenticatedCatalogExtrasRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/beverages': {
      id: '/_authenticated/catalog/beverages'
      path: '/beverages'
      fullPath: '/catalog/beverages'
      preLoaderRoute: typeof AuthenticatedCatalogBeveragesRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCatalogRouteChildren {
  AuthenticatedCatalogBeveragesRoute: typeof AuthenticatedCatalogBeveragesRoute
  AuthenticatedCatalogExtrasRoute: typeof AuthenticatedCatalogExtrasRoute
  AuthenticatedCatalogFoodRoute: typeof AuthenticatedCatalogFoodRoute
  AuthenticatedCatalogRulesRoute: typeof AuthenticatedCatalogRulesRoute
  AuthenticatedCatalogSpacesRoute: typeof AuthenticatedCatalogSpacesRoute
}

const AuthenticatedCatalogRouteChildren: AuthenticatedCatalogRouteChildren = {
  AuthenticatedCatalogBeveragesRoute: AuthenticatedCatalogBeveragesRoute,
  AuthenticatedCatalogExtrasRoute: AuthenticatedCatalogExtrasRoute,
  AuthenticatedCatalogFoodRoute: AuthenticatedCatalogFoodRoute,
  AuthenticatedCatalogRulesRoute: AuthenticatedCatalogRulesRoute,
  AuthenticatedCatalogSpacesRoute: AuthenticatedCatalogSpacesRoute,
}

const AuthenticatedCatalogRouteWithChildren =
  AuthenticatedCatalogRoute._addFileChildren(AuthenticatedCatalogRouteChildren)

interface AuthenticatedDealsRouteChildren {
  AuthenticatedDealsCalendarRoute: typeof AuthenticatedDealsCalendarRoute
  AuthenticatedDealsIndexRoute: typeof AuthenticatedDealsIndexRoute
}

const AuthenticatedDealsRouteChildren: AuthenticatedDealsRouteChildren = {
  AuthenticatedDealsCalendarRoute: AuthenticatedDealsCalendarRoute,
  AuthenticatedDealsIndexRoute: AuthenticatedDealsIndexRoute,
}

const AuthenticatedDealsRouteWithChildren =
  AuthenticatedDealsRoute._addFileChildren(AuthenticatedDealsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRouteWithChildren
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDealsIdRoute: typeof AuthenticatedDealsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCatalogRoute: AuthenticatedCatalogRouteWithChildren,
  AuthenticatedDealsRoute: AuthenticatedDealsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDealsIdRoute: AuthenticatedDealsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CTokenRoute: CTokenRoute,
  DTokenRoute: DTokenRoute,
  FSlugRoute: FSlugRoute,
  PTokenRoute: PTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
