/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedDealsIndexRouteImport } from './routes/_authenticated/deals.index'
import { Route as AuthenticatedSettingsWorkflowRouteImport } from './routes/_authenticated/settings.workflow'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedSettingsLeadFormsRouteImport } from './routes/_authenticated/settings.lead-forms'
import { Route as AuthenticatedSettingsLanguageRouteImport } from './routes/_authenticated/settings.language'
import { Route as AuthenticatedSettingsInvoicingRouteImport } from './routes/_authenticated/settings.invoicing'
import { Route as AuthenticatedSettingsFeesRouteImport } from './routes/_authenticated/settings.fees'
import { Route as AuthenticatedSettingsContractTemplatesRouteImport } from './routes/_authenticated/settings.contract-templates'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings.company'
import { Route as AuthenticatedSettingsBrandRouteImport } from './routes/_authenticated/settings.brand'
import { Route as AuthenticatedDealsIdRouteImport } from './routes/_authenticated/deals_.$id'
import { Route as AuthenticatedDealsCalendarRouteImport } from './routes/_authenticated/deals.calendar'
import { Route as AuthenticatedCatalogStaffRouteImport } from './routes/_authenticated/catalog.staff'
import { Route as AuthenticatedCatalogSpacesRouteImport } from './routes/_authenticated/catalog.spaces'
import { Route as AuthenticatedCatalogRulesRouteImport } from './routes/_authenticated/catalog.rules'
import { Route as AuthenticatedCatalogFoodRouteImport } from './routes/_authenticated/catalog.food'
import { Route as AuthenticatedCatalogExtrasRouteImport } from './routes/_authenticated/catalog.extras'
import { Route as AuthenticatedCatalogBeveragesRouteImport } from './routes/_authenticated/catalog.beverages'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedDealsIndexRoute = AuthenticatedDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDealsRoute,
} as any)
const AuthenticatedSettingsWorkflowRoute =
  AuthenticatedSettingsWorkflowRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLeadFormsRoute =
  AuthenticatedSettingsLeadFormsRouteImport.update({
    id: '/lead-forms',
    path: '/lead-forms',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLanguageRoute =
  AuthenticatedSettingsLanguageRouteImport.update({
    id: '/language',
    path: '/language',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsInvoicingRoute =
  AuthenticatedSettingsInvoicingRouteImport.update({
    id: '/invoicing',
    path: '/invoicing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsFeesRoute =
  AuthenticatedSettingsFeesRouteImport.update({
    id: '/fees',
    path: '/fees',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsContractTemplatesRoute =
  AuthenticatedSettingsContractTemplatesRouteImport.update({
    id: '/contract-templates',
    path: '/contract-templates',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBrandRoute =
  AuthenticatedSettingsBrandRouteImport.update({
    id: '/brand',
    path: '/brand',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedDealsIdRoute = AuthenticatedDealsIdRouteImport.update({
  id: '/deals_/$id',
  path: '/deals/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsCalendarRoute =
  AuthenticatedDealsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedDealsRoute,
  } as any)
const AuthenticatedCatalogStaffRoute =
  AuthenticatedCatalogStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogSpacesRoute =
  AuthenticatedCatalogSpacesRouteImport.update({
    id: '/spaces',
    path: '/spaces',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogRulesRoute =
  AuthenticatedCatalogRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogFoodRoute =
  AuthenticatedCatalogFoodRouteImport.update({
    id: '/food',
    path: '/food',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogExtrasRoute =
  AuthenticatedCatalogExtrasRouteImport.update({
    id: '/extras',
    path: '/extras',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogBeveragesRoute =
  AuthenticatedCatalogBeveragesRouteImport.update({
    id: '/beverages',
    path: '/beverages',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/deals': typeof AuthenticatedDealsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/d/$token': typeof DTokenRoute
  '/f/$slug': typeof FSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$token': typeof PTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/catalog/beverages': typeof AuthenticatedCatalogBeveragesRoute
  '/catalog/extras': typeof AuthenticatedCatalogExtrasRoute
  '/catalog/food': typeof AuthenticatedCatalogFoodRoute
  '/catalog/rules': typeof AuthenticatedCatalogRulesRoute
  '/catalog/spaces': typeof AuthenticatedCatalogSpacesRoute
  '/catalog/staff': typeof AuthenticatedCatalogStaffRoute
  '/deals/calendar': typeof AuthenticatedDealsCalendarRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/contract-templates': typeof AuthenticatedSettingsContractTemplatesRoute
  '/settings/fees': typeof AuthenticatedSettingsFeesRoute
  '/settings/invoicing': typeof AuthenticatedSettingsInvoicingRoute
  '/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/settings/lead-forms': typeof AuthenticatedSettingsLeadFormsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/workflow': typeof AuthenticatedSettingsWorkflowRoute
  '/deals/': typeof AuthenticatedDealsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/d/$token': typeof DTokenRoute
  '/f/$slug': typeof FSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$token': typeof PTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/catalog/beverages': typeof AuthenticatedCatalogBeveragesRoute
  '/catalog/extras': typeof AuthenticatedCatalogExtrasRoute
  '/catalog/food': typeof AuthenticatedCatalogFoodRoute
  '/catalog/rules': typeof AuthenticatedCatalogRulesRoute
  '/catalog/spaces': typeof AuthenticatedCatalogSpacesRoute
  '/catalog/staff': typeof AuthenticatedCatalogStaffRoute
  '/deals/calendar': typeof AuthenticatedDealsCalendarRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/contract-templates': typeof AuthenticatedSettingsContractTemplatesRoute
  '/settings/fees': typeof AuthenticatedSettingsFeesRoute
  '/settings/invoicing': typeof AuthenticatedSettingsInvoicingRoute
  '/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/settings/lead-forms': typeof AuthenticatedSettingsLeadFormsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/workflow': typeof AuthenticatedSettingsWorkflowRoute
  '/deals': typeof AuthenticatedDealsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/_authenticated/deals': typeof AuthenticatedDealsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/d/$token': typeof DTokenRoute
  '/f/$slug': typeof FSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$token': typeof PTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/catalog/beverages': typeof AuthenticatedCatalogBeveragesRoute
  '/_authenticated/catalog/extras': typeof AuthenticatedCatalogExtrasRoute
  '/_authenticated/catalog/food': typeof AuthenticatedCatalogFoodRoute
  '/_authenticated/catalog/rules': typeof AuthenticatedCatalogRulesRoute
  '/_authenticated/catalog/spaces': typeof AuthenticatedCatalogSpacesRoute
  '/_authenticated/catalog/staff': typeof AuthenticatedCatalogStaffRoute
  '/_authenticated/deals/calendar': typeof AuthenticatedDealsCalendarRoute
  '/_authenticated/deals_/$id': typeof AuthenticatedDealsIdRoute
  '/_authenticated/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/contract-templates': typeof AuthenticatedSettingsContractTemplatesRoute
  '/_authenticated/settings/fees': typeof AuthenticatedSettingsFeesRoute
  '/_authenticated/settings/invoicing': typeof AuthenticatedSettingsInvoicingRoute
  '/_authenticated/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/_authenticated/settings/lead-forms': typeof AuthenticatedSettingsLeadFormsRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/settings/workflow': typeof AuthenticatedSettingsWorkflowRoute
  '/_authenticated/deals/': typeof AuthenticatedDealsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analytics'
    | '/catalog'
    | '/deals'
    | '/settings'
    | '/c/$token'
    | '/d/$token'
    | '/f/$slug'
    | '/invite/$token'
    | '/p/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/catalog/beverages'
    | '/catalog/extras'
    | '/catalog/food'
    | '/catalog/rules'
    | '/catalog/spaces'
    | '/catalog/staff'
    | '/deals/calendar'
    | '/deals/$id'
    | '/settings/brand'
    | '/settings/company'
    | '/settings/contract-templates'
    | '/settings/fees'
    | '/settings/invoicing'
    | '/settings/language'
    | '/settings/lead-forms'
    | '/settings/team'
    | '/settings/workflow'
    | '/deals/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analytics'
    | '/catalog'
    | '/c/$token'
    | '/d/$token'
    | '/f/$slug'
    | '/invite/$token'
    | '/p/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/catalog/beverages'
    | '/catalog/extras'
    | '/catalog/food'
    | '/catalog/rules'
    | '/catalog/spaces'
    | '/catalog/staff'
    | '/deals/calendar'
    | '/deals/$id'
    | '/settings/brand'
    | '/settings/company'
    | '/settings/contract-templates'
    | '/settings/fees'
    | '/settings/invoicing'
    | '/settings/language'
    | '/settings/lead-forms'
    | '/settings/team'
    | '/settings/workflow'
    | '/deals'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/analytics'
    | '/_authenticated/catalog'
    | '/_authenticated/deals'
    | '/_authenticated/settings'
    | '/c/$token'
    | '/d/$token'
    | '/f/$slug'
    | '/invite/$token'
    | '/p/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/catalog/beverages'
    | '/_authenticated/catalog/extras'
    | '/_authenticated/catalog/food'
    | '/_authenticated/catalog/rules'
    | '/_authenticated/catalog/spaces'
    | '/_authenticated/catalog/staff'
    | '/_authenticated/deals/calendar'
    | '/_authenticated/deals_/$id'
    | '/_authenticated/settings/brand'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/contract-templates'
    | '/_authenticated/settings/fees'
    | '/_authenticated/settings/invoicing'
    | '/_authenticated/settings/language'
    | '/_authenticated/settings/lead-forms'
    | '/_authenticated/settings/team'
    | '/_authenticated/settings/workflow'
    | '/_authenticated/deals/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CTokenRoute: typeof CTokenRoute
  DTokenRoute: typeof DTokenRoute
  FSlugRoute: typeof FSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PTokenRoute: typeof PTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/deals/': {
      id: '/_authenticated/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof AuthenticatedDealsIndexRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/_authenticated/settings/workflow': {
      id: '/_authenticated/settings/workflow'
      path: '/workflow'
      fullPath: '/settings/workflow'
      preLoaderRoute: typeof AuthenticatedSettingsWorkflowRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/lead-forms': {
      id: '/_authenticated/settings/lead-forms'
      path: '/lead-forms'
      fullPath: '/settings/lead-forms'
      preLoaderRoute: typeof AuthenticatedSettingsLeadFormsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/language': {
      id: '/_authenticated/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AuthenticatedSettingsLanguageRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/invoicing': {
      id: '/_authenticated/settings/invoicing'
      path: '/invoicing'
      fullPath: '/settings/invoicing'
      preLoaderRoute: typeof AuthenticatedSettingsInvoicingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/fees': {
      id: '/_authenticated/settings/fees'
      path: '/fees'
      fullPath: '/settings/fees'
      preLoaderRoute: typeof AuthenticatedSettingsFeesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/contract-templates': {
      id: '/_authenticated/settings/contract-templates'
      path: '/contract-templates'
      fullPath: '/settings/contract-templates'
      preLoaderRoute: typeof AuthenticatedSettingsContractTemplatesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/brand': {
      id: '/_authenticated/settings/brand'
      path: '/brand'
      fullPath: '/settings/brand'
      preLoaderRoute: typeof AuthenticatedSettingsBrandRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/deals_/$id': {
      id: '/_authenticated/deals_/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AuthenticatedDealsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals/calendar': {
      id: '/_authenticated/deals/calendar'
      path: '/calendar'
      fullPath: '/deals/calendar'
      preLoaderRoute: typeof AuthenticatedDealsCalendarRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/_authenticated/catalog/staff': {
      id: '/_authenticated/catalog/staff'
      path: '/staff'
      fullPath: '/catalog/staff'
      preLoaderRoute: typeof AuthenticatedCatalogStaffRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/spaces': {
      id: '/_authenticated/catalog/spaces'
      path: '/spaces'
      fullPath: '/catalog/spaces'
      preLoaderRoute: typeof AuthenticatedCatalogSpacesRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/rules': {
      id: '/_authenticated/catalog/rules'
      path: '/rules'
      fullPath: '/catalog/rules'
      preLoaderRoute: typeof AuthenticatedCatalogRulesRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/food': {
      id: '/_authenticated/catalog/food'
      path: '/food'
      fullPath: '/catalog/food'
      preLoaderRoute: typeof AuthenticatedCatalogFoodRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/extras': {
      id: '/_authenticated/catalog/extras'
      path: '/extras'
      fullPath: '/catalog/extras'
      preLoaderRoute: typeof AuthenticatedCatalogExtrasRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/beverages': {
      id: '/_authenticated/catalog/beverages'
      path: '/beverages'
      fullPath: '/catalog/beverages'
      preLoaderRoute: typeof AuthenticatedCatalogBeveragesRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCatalogRouteChildren {
  AuthenticatedCatalogBeveragesRoute: typeof AuthenticatedCatalogBeveragesRoute
  AuthenticatedCatalogExtrasRoute: typeof AuthenticatedCatalogExtrasRoute
  AuthenticatedCatalogFoodRoute: typeof AuthenticatedCatalogFoodRoute
  AuthenticatedCatalogRulesRoute: typeof AuthenticatedCatalogRulesRoute
  AuthenticatedCatalogSpacesRoute: typeof AuthenticatedCatalogSpacesRoute
  AuthenticatedCatalogStaffRoute: typeof AuthenticatedCatalogStaffRoute
}

const AuthenticatedCatalogRouteChildren: AuthenticatedCatalogRouteChildren = {
  AuthenticatedCatalogBeveragesRoute: AuthenticatedCatalogBeveragesRoute,
  AuthenticatedCatalogExtrasRoute: AuthenticatedCatalogExtrasRoute,
  AuthenticatedCatalogFoodRoute: AuthenticatedCatalogFoodRoute,
  AuthenticatedCatalogRulesRoute: AuthenticatedCatalogRulesRoute,
  AuthenticatedCatalogSpacesRoute: AuthenticatedCatalogSpacesRoute,
  AuthenticatedCatalogStaffRoute: AuthenticatedCatalogStaffRoute,
}

const AuthenticatedCatalogRouteWithChildren =
  AuthenticatedCatalogRoute._addFileChildren(AuthenticatedCatalogRouteChildren)

interface AuthenticatedDealsRouteChildren {
  AuthenticatedDealsCalendarRoute: typeof AuthenticatedDealsCalendarRoute
  AuthenticatedDealsIndexRoute: typeof AuthenticatedDealsIndexRoute
}

const AuthenticatedDealsRouteChildren: AuthenticatedDealsRouteChildren = {
  AuthenticatedDealsCalendarRoute: AuthenticatedDealsCalendarRoute,
  AuthenticatedDealsIndexRoute: AuthenticatedDealsIndexRoute,
}

const AuthenticatedDealsRouteWithChildren =
  AuthenticatedDealsRoute._addFileChildren(AuthenticatedDealsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBrandRoute: typeof AuthenticatedSettingsBrandRoute
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsContractTemplatesRoute: typeof AuthenticatedSettingsContractTemplatesRoute
  AuthenticatedSettingsFeesRoute: typeof AuthenticatedSettingsFeesRoute
  AuthenticatedSettingsInvoicingRoute: typeof AuthenticatedSettingsInvoicingRoute
  AuthenticatedSettingsLanguageRoute: typeof AuthenticatedSettingsLanguageRoute
  AuthenticatedSettingsLeadFormsRoute: typeof AuthenticatedSettingsLeadFormsRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsWorkflowRoute: typeof AuthenticatedSettingsWorkflowRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBrandRoute: AuthenticatedSettingsBrandRoute,
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsContractTemplatesRoute:
    AuthenticatedSettingsContractTemplatesRoute,
  AuthenticatedSettingsFeesRoute: AuthenticatedSettingsFeesRoute,
  AuthenticatedSettingsInvoicingRoute: AuthenticatedSettingsInvoicingRoute,
  AuthenticatedSettingsLanguageRoute: AuthenticatedSettingsLanguageRoute,
  AuthenticatedSettingsLeadFormsRoute: AuthenticatedSettingsLeadFormsRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsWorkflowRoute: AuthenticatedSettingsWorkflowRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRouteWithChildren
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedDealsIdRoute: typeof AuthenticatedDealsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRouteWithChildren,
  AuthenticatedDealsRoute: AuthenticatedDealsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedDealsIdRoute: AuthenticatedDealsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CTokenRoute: CTokenRoute,
  DTokenRoute: DTokenRoute,
  FSlugRoute: FSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  PTokenRoute: PTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
