/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedDealsIndexRouteImport } from './routes/_authenticated/deals.index'
import { Route as AuthenticatedDealsIdRouteImport } from './routes/_authenticated/deals_.$id'
import { Route as AuthenticatedDealsCalendarRouteImport } from './routes/_authenticated/deals.calendar'
import { Route as AuthenticatedCatalogSpacesRouteImport } from './routes/_authenticated/catalog.spaces'
import { Route as AuthenticatedCatalogRulesRouteImport } from './routes/_authenticated/catalog.rules'
import { Route as AuthenticatedCatalogFoodRouteImport } from './routes/_authenticated/catalog.food'
import { Route as AuthenticatedCatalogExtrasRouteImport } from './routes/_authenticated/catalog.extras'
import { Route as AuthenticatedCatalogBeveragesRouteImport } from './routes/_authenticated/catalog.beverages'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsIndexRoute = AuthenticatedDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDealsRoute,
} as any)
const AuthenticatedDealsIdRoute = AuthenticatedDealsIdRouteImport.update({
  id: '/deals_/$id',
  path: '/deals/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsCalendarRoute =
  AuthenticatedDealsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedDealsRoute,
  } as any)
const AuthenticatedCatalogSpacesRoute =
  AuthenticatedCatalogSpacesRouteImport.update({
    id: '/spaces',
    path: '/spaces',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogRulesRoute =
  AuthenticatedCatalogRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogFoodRoute =
  AuthenticatedCatalogFoodRouteImport.update({
    id: '/food',
    path: '/food',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogExtrasRoute =
  AuthenticatedCatalogExtrasRouteImport.update({
    id: '/extras',
    path: '/extras',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)
const AuthenticatedCatalogBeveragesRoute =
  AuthenticatedCatalogBeveragesRouteImport.update({
    id: '/beverages',
    path: '/beverages',
    getParentRoute: () => AuthenticatedCatalogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/deals': typeof AuthenticatedDealsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/d/$token': typeof DTokenRoute
  '/p/$token': typeof PTokenRoute
  '/catalog/beverages': typeof AuthenticatedCatalogBeveragesRoute
  '/catalog/extras': typeof AuthenticatedCatalogExtrasRoute
  '/catalog/food': typeof AuthenticatedCatalogFoodRoute
  '/catalog/rules': typeof AuthenticatedCatalogRulesRoute
  '/catalog/spaces': typeof AuthenticatedCatalogSpacesRoute
  '/deals/calendar': typeof AuthenticatedDealsCalendarRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/deals/': typeof AuthenticatedDealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/d/$token': typeof DTokenRoute
  '/p/$token': typeof PTokenRoute
  '/catalog/beverages': typeof AuthenticatedCatalogBeveragesRoute
  '/catalog/extras': typeof AuthenticatedCatalogExtrasRoute
  '/catalog/food': typeof AuthenticatedCatalogFoodRoute
  '/catalog/rules': typeof AuthenticatedCatalogRulesRoute
  '/catalog/spaces': typeof AuthenticatedCatalogSpacesRoute
  '/deals/calendar': typeof AuthenticatedDealsCalendarRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/deals': typeof AuthenticatedDealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRouteWithChildren
  '/_authenticated/deals': typeof AuthenticatedDealsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/d/$token': typeof DTokenRoute
  '/p/$token': typeof PTokenRoute
  '/_authenticated/catalog/beverages': typeof AuthenticatedCatalogBeveragesRoute
  '/_authenticated/catalog/extras': typeof AuthenticatedCatalogExtrasRoute
  '/_authenticated/catalog/food': typeof AuthenticatedCatalogFoodRoute
  '/_authenticated/catalog/rules': typeof AuthenticatedCatalogRulesRoute
  '/_authenticated/catalog/spaces': typeof AuthenticatedCatalogSpacesRoute
  '/_authenticated/deals/calendar': typeof AuthenticatedDealsCalendarRoute
  '/_authenticated/deals_/$id': typeof AuthenticatedDealsIdRoute
  '/_authenticated/deals/': typeof AuthenticatedDealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/catalog'
    | '/deals'
    | '/settings'
    | '/d/$token'
    | '/p/$token'
    | '/catalog/beverages'
    | '/catalog/extras'
    | '/catalog/food'
    | '/catalog/rules'
    | '/catalog/spaces'
    | '/deals/calendar'
    | '/deals/$id'
    | '/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/catalog'
    | '/settings'
    | '/d/$token'
    | '/p/$token'
    | '/catalog/beverages'
    | '/catalog/extras'
    | '/catalog/food'
    | '/catalog/rules'
    | '/catalog/spaces'
    | '/deals/calendar'
    | '/deals/$id'
    | '/deals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/catalog'
    | '/_authenticated/deals'
    | '/_authenticated/settings'
    | '/d/$token'
    | '/p/$token'
    | '/_authenticated/catalog/beverages'
    | '/_authenticated/catalog/extras'
    | '/_authenticated/catalog/food'
    | '/_authenticated/catalog/rules'
    | '/_authenticated/catalog/spaces'
    | '/_authenticated/deals/calendar'
    | '/_authenticated/deals_/$id'
    | '/_authenticated/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  DTokenRoute: typeof DTokenRoute
  PTokenRoute: typeof PTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals/': {
      id: '/_authenticated/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof AuthenticatedDealsIndexRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/_authenticated/deals_/$id': {
      id: '/_authenticated/deals_/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AuthenticatedDealsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals/calendar': {
      id: '/_authenticated/deals/calendar'
      path: '/calendar'
      fullPath: '/deals/calendar'
      preLoaderRoute: typeof AuthenticatedDealsCalendarRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/_authenticated/catalog/spaces': {
      id: '/_authenticated/catalog/spaces'
      path: '/spaces'
      fullPath: '/catalog/spaces'
      preLoaderRoute: typeof AuthenticatedCatalogSpacesRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/rules': {
      id: '/_authenticated/catalog/rules'
      path: '/rules'
      fullPath: '/catalog/rules'
      preLoaderRoute: typeof AuthenticatedCatalogRulesRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/food': {
      id: '/_authenticated/catalog/food'
      path: '/food'
      fullPath: '/catalog/food'
      preLoaderRoute: typeof AuthenticatedCatalogFoodRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/extras': {
      id: '/_authenticated/catalog/extras'
      path: '/extras'
      fullPath: '/catalog/extras'
      preLoaderRoute: typeof AuthenticatedCatalogExtrasRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
    '/_authenticated/catalog/beverages': {
      id: '/_authenticated/catalog/beverages'
      path: '/beverages'
      fullPath: '/catalog/beverages'
      preLoaderRoute: typeof AuthenticatedCatalogBeveragesRouteImport
      parentRoute: typeof AuthenticatedCatalogRoute
    }
  }
}

interface AuthenticatedCatalogRouteChildren {
  AuthenticatedCatalogBeveragesRoute: typeof AuthenticatedCatalogBeveragesRoute
  AuthenticatedCatalogExtrasRoute: typeof AuthenticatedCatalogExtrasRoute
  AuthenticatedCatalogFoodRoute: typeof AuthenticatedCatalogFoodRoute
  AuthenticatedCatalogRulesRoute: typeof AuthenticatedCatalogRulesRoute
  AuthenticatedCatalogSpacesRoute: typeof AuthenticatedCatalogSpacesRoute
}

const AuthenticatedCatalogRouteChildren: AuthenticatedCatalogRouteChildren = {
  AuthenticatedCatalogBeveragesRoute: AuthenticatedCatalogBeveragesRoute,
  AuthenticatedCatalogExtrasRoute: AuthenticatedCatalogExtrasRoute,
  AuthenticatedCatalogFoodRoute: AuthenticatedCatalogFoodRoute,
  AuthenticatedCatalogRulesRoute: AuthenticatedCatalogRulesRoute,
  AuthenticatedCatalogSpacesRoute: AuthenticatedCatalogSpacesRoute,
}

const AuthenticatedCatalogRouteWithChildren =
  AuthenticatedCatalogRoute._addFileChildren(AuthenticatedCatalogRouteChildren)

interface AuthenticatedDealsRouteChildren {
  AuthenticatedDealsCalendarRoute: typeof AuthenticatedDealsCalendarRoute
  AuthenticatedDealsIndexRoute: typeof AuthenticatedDealsIndexRoute
}

const AuthenticatedDealsRouteChildren: AuthenticatedDealsRouteChildren = {
  AuthenticatedDealsCalendarRoute: AuthenticatedDealsCalendarRoute,
  AuthenticatedDealsIndexRoute: AuthenticatedDealsIndexRoute,
}

const AuthenticatedDealsRouteWithChildren =
  AuthenticatedDealsRoute._addFileChildren(AuthenticatedDealsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRouteWithChildren
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDealsIdRoute: typeof AuthenticatedDealsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCatalogRoute: AuthenticatedCatalogRouteWithChildren,
  AuthenticatedDealsRoute: AuthenticatedDealsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDealsIdRoute: AuthenticatedDealsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  DTokenRoute: DTokenRoute,
  PTokenRoute: PTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
